//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHeroCala
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperHero
    {
        public int ID { get; set; }
        public string superHeroName { get; set; }
        public string alterEgo { get; set; }
        public string primarySuperHeroAbility { get; set; }
        public string secondarySuperHeroAbility { get; set; }
        public string catchPhrase { get; set; }
    }
}
